name: Deploy to GCP
on:
  workflow_dispatch: # Allows manual triggering from the GitHub Actions UI

permissions:
  contents: read
  id-token: write # Required for requesting the JWT

jobs:
  auth-test:
    runs-on: ubuntu-latest
    env:
      TF_VAR_project_id: ${{ secrets.GCP_PROJECT_ID }}
      TF_VAR_terraform_service_account: ${{ secrets.GCP_SA_EMAIL }}
      TF_VAR_network_project_id: 'daston-a-dev-net-dev-0'
      TF_VAR_subnet_name: 'dev-default'
      TF_VAR_region: 'us-central1'
      TF_VAR_zone: 'us-central1-a'
      TF_VAR_create_linux_vm: true
      TF_VAR_create_windows_vm: false
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Google Auth
      id: auth
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
        service_account: ${{ secrets.GCP_SA_EMAIL }}

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'

    - name: 'Verify Auth'
      run: 'gcloud auth list'

    - name: 'Set up Terraform'
      uses: hashicorp/setup-terraform@v3

    - name: 'Terraform Init'
      working-directory: ./gce
      run: |
        cat <<EOF > backend.conf
        bucket = "${{ secrets.GCP_STATE_BUCKET }}"
        EOF
        terraform init -backend-config=backend.conf

    - name: 'Terraform Plan'
      working-directory: ./gce
      run: terraform plan

    - name: 'Terraform Apply'
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      working-directory: ./gce
      run: terraform apply -auto-approve
